[build]
  publish = "build/"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/spreadsheets/*"
  to = "https://docs.google.com"
  status = 200
